markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : AirForge
production_url : http://airforge.github.io
description: "Just trying to build stuff."
disqus_shortname: airforge
#analytics: UA-32899481-1
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Ben Baltes
  github : airforge
#  twitter : caarlos0
  email: benbaltes@utexas.edu
